version: "3.3"
services:
  app:
    build:
      context: . #current directory
      dockerfile: Dockerfile #use the dockerfile called Dockerfile
    container_name: ip_location_mapper
    ports:
      - "3000:3000" #forward port from my app to the OS
    environment: # Pass environment variables to the service
      REDIS_ADDRESS: ${REDIS_ADDRESS}
      REDIS_PASS: ${REDIS_PASS}
      API_CURRCONV: ${API_CURRCONV}
      API_IPFY: ${API_IPFY}
      LIMIT_COMMAND: ${LIMIT_COMMAND}
      LIMIT_REQUEST: ${LIMIT_REQUEST}
      SERVER_PORT: ${SERVER_PORT}